### PR TITLE
Update :allthethings:

### PR DESCRIPTION
**Pull request by Jawnnypoo**
This PR basically updates dependencies so that future PRs will not have to deal with this problem. Only real code change is the fact that FloatMath was removed in API 23, so we revert to Math instead, casting results as floats. It also adds `gradlew.bat` so that Windows users can build from the command line :smile:

### CODE REVIEW

**Comment by Jawnnypoo** [comment]
I also went ahead and removed the custom SlidingTabLayout and replaced it with a TabLayout for the sake of consistency.

**Comment by romannurik** [comment]
Unlikely that I'll be making additional pushes to the Play Store any time soon, but good to keep the repo up to date :)

**Comment by romannurik** [comment]
oh and thank you!

**Comment by Jawnnypoo** [comment]
No prob! Love the watchface! Was exploring how it was done and figured I could make the updates. It would be awesome to turn the current Google I/O countdown into a watchface 😁

**Pull request merged**
